/// Returns training text - a collection of English prose/poetry patterns
pub fn get_training_data() -> &'static str {
    // Using a mix of simple English patterns that a tiny model can learn
    concat!(
        "To be or not to be that is the question\n",
        "Whether tis nobler in the mind to suffer\n",
        "The slings and arrows of outrageous fortune\n",
        "Or to take arms against a sea of troubles\n",
        "And by opposing end them to die to sleep\n",
        "No more and by a sleep to say we end\n",
        "The heartache and the thousand natural shocks\n",
        "That flesh is heir to tis a consummation\n",
        "Devoutly to be wished to die to sleep\n",
        "To sleep perchance to dream ay there the rub\n",
        "For in that sleep of death what dreams may come\n",
        "When we have shuffled off this mortal coil\n",
        "Must give us pause there the respect\n",
        "That makes calamity of so long life\n",
        "For who would bear the whips and scorns of time\n",
        "The oppressor wrong the proud man contumely\n",
        "The pangs of despised love the law delay\n",
        "The insolence of office and the spurns\n",
        "That patient merit of the unworthy takes\n",
        "When he himself might his quietus make\n",
        "With a bare bodkin who would fardels bear\n",
        "To grunt and sweat under a weary life\n",
        "But that the dread of something after death\n",
        "The undiscovered country from whose bourn\n",
        "No traveller returns puzzles the will\n",
        "And makes us rather bear those ills we have\n",
        "Than fly to others that we know not of\n",
        "Thus conscience does make cowards of us all\n",
        "And thus the native hue of resolution\n",
        "Is sicklied over with the pale cast of thought\n",
        "And enterprises of great pith and moment\n",
        "With this regard their currents turn awry\n",
        "And lose the name of action\n",
        "All the world is a stage\n",
        "And all the men and women merely players\n",
        "They have their exits and their entrances\n",
        "And one man in his time plays many parts\n",
        "His acts being seven ages at first the infant\n",
        "Mewling and puking in the nurse arms\n",
        "Then the whining school boy with his satchel\n",
        "And shining morning face creeping like snail\n",
        "Unwillingly to school and then the lover\n",
        "Sighing like furnace with a woeful ballad\n",
        "Made to his mistress eyebrow then a soldier\n",
        "Full of strange oaths and bearded like the pard\n",
        "Jealous in honour sudden and quick in quarrel\n",
        "Seeking the bubble reputation\n",
        "Even in the cannon mouth and then the justice\n",
        "In fair round belly with good capon lined\n",
        "With eyes severe and beard of formal cut\n",
        "Full of wise saws and modern instances\n",
        "And so he plays his part the sixth age shifts\n",
        "Into the lean and slippered pantaloon\n",
        "With spectacles on nose and pouch on side\n",
        "His youthful hose well saved a world too wide\n",
        "For his shrunk shank and his big manly voice\n",
        "Turning again toward childish treble pipes\n",
        "And whistles in his sound last scene of all\n",
        "That ends this strange eventful history\n",
        "Is second childishness and mere oblivion\n",
        "Sans teeth sans eyes sans taste sans everything\n",
        "Friends countrymen lend me your ears\n",
        "I come to bury not to praise him\n",
        "The evil that men do lives after them\n",
        "The good is oft interred with their bones\n",
        "So let it be with the noble one\n",
        "The noble one was my friend faithful and just to me\n",
        "But the honourable man says he was ambitious\n",
        "And the honourable man is an honourable man\n",
        "He hath brought many captives home to the city\n",
        "Whose ransoms did the general coffers fill\n",
        "Did this in him seem ambitious\n",
        "When that the poor have cried he hath wept\n",
        "Ambition should be made of sterner stuff\n",
        "Yet the honourable man says he was ambitious\n",
        "You all did see that on the feast day\n",
        "I thrice presented him a kingly crown\n",
        "Which he did thrice refuse was this ambition\n",
        "Yet the honourable man says he was ambitious\n",
        "I speak not to disprove what was spoke\n",
        "But here I am to speak what I do know\n",
        "You all did love him once not without cause\n",
        "What cause withholds you then to mourn for him\n",
        "O judgement thou art fled to brutish beasts\n",
        "And men have lost their reason bear with me\n",
        "My heart is in the coffin there\n",
        "And I must pause till it come back to me\n",
        "If music be the food of love play on\n",
        "Give me excess of it that surfeiting\n",
        "The appetite may sicken and so die\n",
        "That strain again it had a dying fall\n",
        "O it came over my ear like the sweet sound\n",
        "That breathes upon a bank of violets\n",
        "Stealing and giving odour enough no more\n",
        "Tis not so sweet now as it was before\n",
        "O spirit of love how quick and fresh art thou\n",
        "That notwithstanding thy capacity\n",
        "Receiveth as the sea nought enters there\n",
        "Of what validity and pitch so ever\n",
        "But falls into abatement and low price\n",
        "Even in a minute so full of shapes is fancy\n",
        "That it alone is high fantastical\n",
        "Now is the winter of our discontent\n",
        "Made glorious summer by this sun of york\n",
        "And all the clouds that loured upon our house\n",
        "In the deep bosom of the ocean buried\n",
        "Now are our brows bound with victorious wreaths\n",
        "Our bruised arms hung up for monuments\n",
        "Our stern alarums changed to merry meetings\n",
        "Our dreadful marches to delightful measures\n",
        "Grim visaged war hath smoothed his wrinkled front\n",
        "And now instead of mounting barbed steeds\n",
        "To fright the souls of fearful adversaries\n",
        "He capers nimbly in a lady chamber\n",
        "To the lascivious pleasing of a lute\n",
        "But I that am not shaped for sportive tricks\n",
        "Nor made to court an amorous looking glass\n",
        "I that am rudely stamped and want love majesty\n",
        "To strut before a wanton ambling nymph\n",
        "I that am curtailed of this fair proportion\n",
        "Cheated of feature by dissembling nature\n",
        "Deformed unfinished sent before my time\n",
        "Into this breathing world scarce half made up\n",
        "And that so lamely and unfashionable\n",
        "That dogs bark at me as I halt by them\n",
        "Why I in this weak piping time of peace\n",
        "Have no delight to pass away the time\n",
        "Unless to spy my shadow in the sun\n",
        "And descant on mine own deformity\n",
        "And therefore since I cannot prove a lover\n",
        "To entertain these fair well spoken days\n",
        "I am determined to prove a villain\n",
        "And hate the idle pleasures of these days\n",
        "Shall I compare thee to a summer day\n",
        "Thou art more lovely and more temperate\n",
        "Rough winds do shake the darling buds of may\n",
        "And summer lease hath all too short a date\n",
        "Sometime too hot the eye of heaven shines\n",
        "And often is his gold complexion dimmed\n",
        "And every fair from fair sometime declines\n",
        "By chance or nature changing course untrimmed\n",
        "But thy eternal summer shall not fade\n",
        "Nor lose possession of that fair thou owest\n",
        "Nor shall death brag thou wanderest in his shade\n",
        "When in eternal lines to time thou growest\n",
        "So long as men can breathe or eyes can see\n",
        "So long lives this and this gives life to thee\n",
        "Let me not to the marriage of true minds\n",
        "Admit impediments love is not love\n",
        "Which alters when it alteration finds\n",
        "Or bends with the remover to remove\n",
        "O no it is an ever fixed mark\n",
        "That looks on tempests and is never shaken\n",
        "It is the star to every wandering bark\n",
        "Whose worth unknown although his height be taken\n",
        "Love not time fool though rosy lips and cheeks\n",
        "Within his bending sickle compass come\n",
        "Love alters not with his brief hours and weeks\n",
        "But bears it out even to the edge of doom\n",
        "If this be error and upon me proved\n",
        "I never writ nor no man ever loved\n",
        "O Romeo Romeo wherefore art thou Romeo\n",
        "Deny thy father and refuse thy name\n",
        "Or if thou wilt not be but sworn my love\n",
        "And I shall no longer be a foe\n",
        "Tis but thy name that is my enemy\n",
        "Thou art thyself though not a name\n",
        "What is a name that which we call a rose\n",
        "By any other name would smell as sweet\n",
        "So would were he not called so\n",
        "Retain that dear perfection which he owes\n",
        "Without that title Romeo doff thy name\n",
        "And for that name which is no part of thee\n",
        "Take all myself\n",
        "I take thee at thy word\n",
        "Call me but love and I shall be new baptized\n",
        "Henceforth I never will be Romeo\n",
        "What man art thou that thus bescreened in night\n",
        "So stumblest on my counsel\n",
        "By a name I know not how to tell thee who I am\n",
        "My name dear saint is hateful to myself\n",
        "Because it is an enemy to thee\n",
        "Had I it written I would tear the word\n",
        "My ears have not yet drunk a hundred words\n",
        "Of that tongue utterance yet I know the sound\n",
        "Art thou not Romeo and a noble man\n",
        "Neither fair saint if either thee dislike\n",
        "How camest thou hither tell me and wherefore\n",
        "The orchard walls are high and hard to climb\n",
        "And the place death considering who thou art\n",
        "If any of my kinsmen find thee here\n",
        "With love light wings did I overperch these walls\n",
        "For stony limits cannot hold love out\n",
        "And what love can do that dares love attempt\n",
        "Therefore thy kinsmen are no let to me\n",
        "If they do see thee they will murder thee\n",
        "Alack there lies more peril in thine eye\n",
        "Than twenty of their swords look thou but sweet\n",
        "And I am proof against their enmity\n",
        "I would not for the world they saw thee here\n",
        "I have night cloak to hide me from their sight\n",
        "And but thou love me let them find me here\n",
        "My life were better ended by their hate\n",
        "Than death prorogued wanting of thy love\n",
        "By whose direction found thou out this place\n",
        "By love who first did prompt me to inquire\n",
        "He lent me counsel and I lent him eyes\n",
        "I am no pilot yet wert thou as far\n",
        "As that vast shore washed with the farthest sea\n",
        "I would adventure for such merchandise\n",
        "Thou knowest the mask of night is on my face\n",
        "Else would a maiden blush bepaint my cheek\n",
        "For that which thou hast heard me speak tonight\n",
        "Fain would I dwell on form fain fain deny\n",
        "What I have spoke but farewell compliment\n",
        "Dost thou love me I know thou wilt say ay\n",
        "And I will take thy word yet if thou swearest\n",
        "Thou mayst prove false at lovers perjuries\n",
        "They say the heavens themselves do laugh\n",
        "O gentle Romeo if thou dost love pronounce it faithfully\n",
        "Or if thou thinkest I am too quickly won\n",
        "I shall frown and be perverse and say thee nay\n",
        "So thou wilt woo but else not for the world\n",
        "In truth fair one I am too fond\n",
        "And therefore thou mayst think my behaviour light\n",
        "But trust me gentleman I shall prove more true\n",
        "Than those that have more cunning to be strange\n",
        "Good night good night parting is such sweet sorrow\n",
        "That I shall say good night till it be morrow\n",
        "Sleep dwell upon thine eyes peace in thy breast\n",
        "Would I were sleep and peace so sweet to rest\n",
    )
}

/// Create a batch of (input, target) pairs from encoded text
/// Each input is block_size tokens, target is the next token after each position
pub fn create_batches(
    encoded: &[usize],
    block_size: usize,
    batch_size: usize,
    rng: &mut impl rand::Rng,
) -> (Vec<Vec<usize>>, Vec<Vec<usize>>) {
    let max_start = encoded.len() - block_size - 1;
    let mut inputs = Vec::with_capacity(batch_size);
    let mut targets = Vec::with_capacity(batch_size);

    for _ in 0..batch_size {
        let start = rng.gen_range(0..max_start);
        inputs.push(encoded[start..start + block_size].to_vec());
        targets.push(encoded[start + 1..start + block_size + 1].to_vec());
    }

    (inputs, targets)
}
